Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "public_network", bridge:"Realtek PCIe GbE Family Controller", ip: "192.168.1.50", guest:80, host:8080, auto_correct: true
  config.vm.synced_folder ".", "/var/tmp/vagrant"  
config.vm.provider "virtualbox" do |vb|
  vb.memory = "8192" 
end
config.vm.provision "file", source: "../website/unix/index_unix.php", destination: "/var/tmp/vagrant/html/index.php"
config.vm.provision "file", source: "../website/unix/get_price_unix.py", destination: "/var/tmp/vagrant/html/python/get_price.py"
config.vm.provision "file", source: "../website/unix/apache2.conf", destination: "/var/tmp/vagrant/html/apache2.conf"
config.vm.provision "file", source: "../website/unix/.htaccess_unix", destination: "/var/tmp/vagrant/html/.htaccess"
config.vm.provision "file", source: "../website/unix/.htpasswd", destination: "/var/tmp/vagrant/html/.htpasswd"
config.vm.provision "file", source: "../website/css/style.css", destination: "/var/tmp/vagrant/html/css/style.css"
config.vm.provision "file", source: "../website/pictures/background.jpg", destination: "/var/tmp/vagrant/html/pictures/background.jpg"
config.vm.provision "file", source: "../samba/smb.conf", destination: "/var/tmp/vagrant/samba/smb.conf"
config.vm.provision "file", source: "../samba/pw.sh", destination: "/var/tmp/vagrant/samba/pw.sh"
config.vm.provision "shell", inline: <<-SHELL
  #Updaten
  sudo apt-get update
  sudo apt-get -y upgrade

  #python3.6 installieren
  sudo add-apt-repository ppa:deadsnakes/ppa  
  sudo apt-get update  
  sudo apt-get -y install python3.6
  wget https://bootstrap.pypa.io/get-pip.py
  sudo python3.6 get-pip.py
  sudo python3.6 -m pip install yahoo_fin

  #Apache2 und php installieren
  sudo apt-get -y install apache2
  sudo apt -y install apache2 php libapache2-mod-php
  
  # Dateien verschieben
  sudo mv /var/tmp/vagrant/html/apache2.conf /etc/apache2/apache2.conf
  sudo mv -v /var/tmp/vagrant/html/* /var/www/html
  sudo mv /var/tmp/vagrant/html/.ht* /var/www/html/
  sudo rm /var/www/html/index.html
  sudo mkdir /var/www/html/python/tmp
  sudo touch /var/www/html/python/tmp/price
  sudo touch /var/www/html/python/tmp/stock
  sudo chmod 777 /var/www/*
  sudo chmod 777 /var/www/html/python/tmp/*

  # Restart apache
  sudo service apache2 restart

  #Samba installation
  sudo chmod 777 /etc/samba/pw.sh
  sudo apt install -y samba  
  sudo mv /var/tmp/vagrant/samba/smb.conf /etc/samba/smb.conf
  sudo mv /var/tmp/vagrant/samba/pw.sh /etc/samba/pw.sh
  sudo /etc/samba/pw.sh
  sudo service smbd restart

  #Firewall Regeln
  echo "y" | sudo ufw enable
  sudo ufw allow samba
  sudo ufw allow apache
  sudo ufw allow ssh
SHELL
end