Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "public_network", guest:80, host:8080, auto_correct: true
  config.vm.synced_folder ".", "/var/www/html"  
config.vm.provider "virtualbox" do |vb|
  vb.memory = "1024" 
end
config.vm.provision "file", source: "../website/index.php", destination: "/var/www/html/index.php"
config.vm.provision "file", source: "../website/python/get_price.py", destination: "/var/www/html/python/get_price.py"
config.vm.provision "shell", inline: <<-SHELL
  # Packages vom lokalen Server holen
  # sudo sed -i -e"1i deb {{config.server}}/apt-mirror/mirror/archive.ubuntu.com/ubuntu xenial main restricted" /etc/apt/sources.list 
  sudo apt-get update
  sudo apt-get -y install apache2
  sudo apt-get -y install python-pip
  pip install yahoo_finance
  sudo mkdir /var/www/html/python
  sudo mkdir /var/www/html/python/tmp
  sudo mkdir /var/www/html/pictures
  sudo mkdir /var/www/html/css
SHELL
end

